import { 
  Animal, 
  MilkRecord, 
  WeightRecord, 
  ReproductionEvent, 
  HealthRecord, 
  Pasture, 
  InventoryItem, 
  FinancialTransaction, 
  TaskAssignment, 
  FarmProfile,
  SemenStraw
} from '../types/livestock';

export const INITIAL_FARM: FarmProfile = {
  id: 'farm-01',
  name: 'Hacienda La Pradera & San Jerónimo',
  legalId: 'AGRO-900451280-4',
  location: 'Valle del Cauca / Magdalena Medio',
  totalAreaHa: 145,
  grazingAreaHa: 120,
  currency: 'USD',
  systemType: 'Doble Propósito',
  ownerName: 'Dr. Alejandro Restrepo G.',
  managerName: 'Carlos M. Mendoza (Zootecnista)',
  phone: '+57 312 849 2031'
};

export const INITIAL_ANIMALS: Animal[] = [
  {
    id: 'anim-01',
    tagNumber: 'CO-104',
    electronicId: '982.000341892110',
    tattoo: 'T-104',
    name: 'Mariposa Girolando',
    breed: 'Girolando',
    category: 'vaca_produccion',
    sex: 'F',
    birthDate: '2021-04-12',
    weightKg: 540,
    bodyCondition: 3.5,
    purpose: 'leche',
    reproductiveStatus: 'gestante',
    productionStatus: 'ordeño',
    pastureId: 'past-01',
    lotName: 'Lote Ordeño Principal',
    damTag: 'CO-022',
    sireTag: 'SEMEN-HOL-CHIEF',
    geneticOrigin: 'nacido_finca',
    healthStatus: 'sano',
    totalLactations: 3,
    lastCalvingDate: '2026-03-10',
    lastServiceDate: '2026-06-25',
    estimatedCalvingDate: '2027-04-04',
    notes: 'Alta productora. Pico de lactancia en 24 L/día. Excelente ubre y aplomos.',
    createdAt: '2023-01-15'
  },
  {
    id: 'anim-02',
    tagNumber: 'CO-109',
    electronicId: '982.000341892115',
    tattoo: 'T-109',
    name: 'Esmeralda Gyr',
    breed: 'Gyr Lechero',
    category: 'vaca_produccion',
    sex: 'F',
    birthDate: '2020-08-20',
    weightKg: 510,
    bodyCondition: 3.25,
    purpose: 'leche',
    reproductiveStatus: 'inseminada',
    productionStatus: 'ordeño',
    pastureId: 'past-01',
    lotName: 'Lote Ordeño Principal',
    damTag: 'GYR-998',
    sireTag: 'GYR-JAGUAR',
    geneticOrigin: 'comprado_feria',
    purchasePrice: 2200,
    purchaseDate: '2022-11-10',
    healthStatus: 'sano',
    totalLactations: 4,
    lastCalvingDate: '2026-04-15',
    lastServiceDate: '2026-08-30',
    estimatedCalvingDate: '2027-06-09',
    notes: 'Gran rusticidad y tolerancia al calor. Leche con alto % de grasa (4.4%).',
    createdAt: '2022-11-12'
  },
  {
    id: 'anim-03',
    tagNumber: 'CO-115',
    electronicId: '982.000341892121',
    tattoo: 'T-115',
    name: 'Paloma Blanca',
    breed: 'Holstein',
    category: 'vaca_produccion',
    sex: 'F',
    birthDate: '2022-01-10',
    weightKg: 580,
    bodyCondition: 3.0,
    purpose: 'leche',
    reproductiveStatus: 'vacia',
    productionStatus: 'ordeño',
    pastureId: 'past-01',
    lotName: 'Lote Ordeño Principal',
    damTag: 'HOL-401',
    sireTag: 'SEMEN-HOL-KINGBOY',
    geneticOrigin: 'nacido_finca',
    healthStatus: 'en_tratamiento',
    activeTreatmentName: 'Cefalexina intramamaria (Mastitis subclínica cuarto posterior derecho)',
    withdrawalEndDate: '2026-10-06', // Alerta de retiro de leche activa
    totalLactations: 2,
    lastCalvingDate: '2026-07-02',
    notes: 'EN TRATAMIENTO: NO enviar leche a tanque comercial hasta fin de retiro.',
    createdAt: '2023-05-01'
  },
  {
    id: 'anim-04',
    tagNumber: 'CO-128',
    electronicId: '982.000341892134',
    tattoo: 'T-128',
    name: 'Gitana Criolla',
    breed: 'Doble Propósito',
    category: 'vaca_seca',
    sex: 'F',
    birthDate: '2019-11-05',
    weightKg: 525,
    bodyCondition: 3.75,
    purpose: 'doble_proposito',
    reproductiveStatus: 'en_secado',
    productionStatus: 'seca',
    pastureId: 'past-03',
    lotName: 'Lote Vacas Horras y Escoteras',
    damTag: 'CO-011',
    sireTag: 'BR-901',
    geneticOrigin: 'nacido_finca',
    healthStatus: 'sano',
    totalLactations: 5,
    lastCalvingDate: '2025-08-14',
    lastServiceDate: '2026-01-12',
    estimatedCalvingDate: '2026-10-22', // Parto inminente
    notes: 'Fecha probable de parto en menos de 20 días. Preparar potrero de maternidad.',
    createdAt: '2021-02-10'
  },
  {
    id: 'anim-05',
    tagNumber: 'CO-201',
    electronicId: '982.000341892201',
    tattoo: 'T-201',
    name: 'Rey Brahman',
    breed: 'Brahman',
    category: 'toro_reproductor',
    sex: 'M',
    birthDate: '2021-02-18',
    weightKg: 890,
    bodyCondition: 4.0,
    purpose: 'genetica',
    reproductiveStatus: 'parida', // irrelevant for male, set standard
    productionStatus: 'reproductor',
    pastureId: 'past-04',
    lotName: 'Lote Reproductores Elite',
    damTag: 'BR-DONA-LUCIA',
    sireTag: 'BR-MR-V8-SUPERIOR',
    geneticOrigin: 'comprado_feria',
    purchasePrice: 4500,
    purchaseDate: '2023-04-10',
    healthStatus: 'sano',
    notes: 'Toro reproductor registrado. Examen andrológico excelente (Motilidad 85%).',
    createdAt: '2023-04-12'
  },
  {
    id: 'anim-06',
    tagNumber: 'CO-305',
    electronicId: '982.000341892305',
    tattoo: 'N-305',
    name: 'Novillo Campeón',
    breed: 'Brangus',
    category: 'novillo_ceba',
    sex: 'M',
    birthDate: '2025-01-15',
    weightKg: 420,
    bodyCondition: 4.25,
    purpose: 'carne',
    reproductiveStatus: 'vacia',
    productionStatus: 'ceba',
    pastureId: 'past-02',
    lotName: 'Lote Engorde Lote A',
    damTag: 'BR-110',
    sireTag: 'ANGUS-BLACK-POWER',
    geneticOrigin: 'nacido_finca',
    healthStatus: 'sano',
    notes: 'Ganancia de peso récord (1.15 kg/día). Peso meta de faena: 480 kg.',
    createdAt: '2025-01-16'
  },
  {
    id: 'anim-07',
    tagNumber: 'CO-308',
    electronicId: '982.000341892308',
    tattoo: 'N-308',
    name: 'Novillo F1 Nelore',
    breed: 'Nelore',
    category: 'novillo_ceba',
    sex: 'M',
    birthDate: '2025-02-04',
    weightKg: 395,
    bodyCondition: 3.75,
    purpose: 'carne',
    reproductiveStatus: 'vacia',
    productionStatus: 'ceba',
    pastureId: 'past-02',
    lotName: 'Lote Engorde Lote A',
    damTag: 'NEL-55',
    sireTag: 'NEL-TITAN',
    geneticOrigin: 'nacido_finca',
    healthStatus: 'sano',
    notes: 'Rústico y de rápida conversión alimenticia en pastoreo intensivo.',
    createdAt: '2025-02-05'
  },
  {
    id: 'anim-08',
    tagNumber: 'CO-402',
    electronicId: '982.000341892402',
    name: 'Princesa Simmental',
    breed: 'Simmental',
    category: 'novilla_vientre',
    sex: 'F',
    birthDate: '2024-09-12',
    weightKg: 360,
    bodyCondition: 3.5,
    purpose: 'doble_proposito',
    reproductiveStatus: 'celo',
    productionStatus: 'crecimiento',
    pastureId: 'past-05',
    lotName: 'Lote Reemplazos y Novillas',
    damTag: 'CO-080',
    sireTag: 'SIMM-BARON',
    geneticOrigin: 'nacido_finca',
    healthStatus: 'sano',
    notes: 'Alcanzó peso apto para servicio (350kg+). Detectado celo matutino.',
    createdAt: '2024-09-15'
  },
  {
    id: 'anim-09',
    tagNumber: 'CO-510',
    name: 'Ternera Estrella',
    breed: 'Jersey',
    category: 'ternera_leche',
    sex: 'F',
    birthDate: '2026-08-10',
    weightKg: 58,
    bodyCondition: 3.5,
    purpose: 'leche',
    reproductiveStatus: 'vacia',
    productionStatus: 'crecimiento',
    pastureId: 'past-06',
    lotName: 'Lote Sala Cuna / Terneras',
    damTag: 'CO-104',
    sireTag: 'JERSEY-CHROME',
    geneticOrigin: 'nacido_finca',
    healthStatus: 'sano',
    notes: 'Hija de Mariposa. Alimentada con 4L leche + concentrado de iniciación.',
    createdAt: '2026-08-11'
  },
  {
    id: 'anim-10',
    tagNumber: 'CO-512',
    name: 'Ternero Fuerte',
    breed: 'Brahman',
    category: 'ternero_cria',
    sex: 'M',
    birthDate: '2026-08-25',
    weightKg: 64,
    bodyCondition: 3.5,
    purpose: 'carne',
    reproductiveStatus: 'vacia',
    productionStatus: 'crecimiento',
    pastureId: 'past-06',
    lotName: 'Lote Sala Cuna / Terneras',
    damTag: 'CO-109',
    sireTag: 'CO-201',
    geneticOrigin: 'nacido_finca',
    healthStatus: 'sano',
    notes: 'Hijo del toro Rey Brahman. Descornado y tatuado.',
    createdAt: '2026-08-26'
  }
];

export const INITIAL_PASTURES: Pasture[] = [
  {
    id: 'past-01',
    name: 'Potrero El Trébol (Ordeño)',
    code: 'POT-01',
    areaHa: 12.5,
    grassType: 'Brachiaria Brizantha cv. Marandú + Kudzú Tropical',
    carryingCapacityUGM: 25,
    status: 'ocupado',
    entryDate: '2026-10-01',
    daysOccupied: 3,
    targetRestDays: 30,
    forageEstimateKgM2: 2.8,
    waterSource: 'bebedero_automatico',
    shadePercent: 20,
    notes: 'Potrero contiguo a sala de ordeño con cerca eléctrica doble hilo.'
  },
  {
    id: 'past-02',
    name: 'Potrero La Vega (Ceba Intensiva)',
    code: 'POT-02',
    areaHa: 18.0,
    grassType: 'Mombaza (Panicum maximum)',
    carryingCapacityUGM: 38,
    status: 'ocupado',
    entryDate: '2026-09-28',
    daysOccupied: 6,
    targetRestDays: 32,
    forageEstimateKgM2: 3.4,
    waterSource: 'tanque_australiano',
    shadePercent: 25,
    notes: 'Excelente volumen forrajero. Rotación cada 7 días máximo.'
  },
  {
    id: 'past-03',
    name: 'Potrero Las Palmas (Escoteras)',
    code: 'POT-03',
    areaHa: 15.0,
    grassType: 'Brachiaria Decumbens',
    carryingCapacityUGM: 22,
    status: 'ocupado',
    entryDate: '2026-09-20',
    daysOccupied: 14,
    targetRestDays: 35,
    forageEstimateKgM2: 2.1,
    waterSource: 'represa',
    shadePercent: 35,
    notes: 'Abundante sombra natural de palmas de corozo.'
  },
  {
    id: 'past-04',
    name: 'Potrero El Repostero (Toros)',
    code: 'POT-04',
    areaHa: 8.0,
    grassType: 'Estrella Africana (Cynodon nlemfuensis)',
    carryingCapacityUGM: 14,
    status: 'ocupado',
    entryDate: '2026-09-15',
    daysOccupied: 19,
    targetRestDays: 28,
    forageEstimateKgM2: 2.6,
    waterSource: 'bebedero_automatico',
    shadePercent: 30,
    notes: 'Cerca perimetral reforzada con madera tratada y 5 hilos de púa.'
  },
  {
    id: 'past-05',
    name: 'Potrero Los Samanes (Novillas)',
    code: 'POT-05',
    areaHa: 14.0,
    grassType: 'Mulato II (Híbrido Brachiaria)',
    carryingCapacityUGM: 26,
    status: 'descanso',
    targetRestDays: 30,
    forageEstimateKgM2: 3.1,
    waterSource: 'quebrada',
    shadePercent: 40,
    notes: 'En día 22 de descanso. Listo para entrada en 8 días.'
  },
  {
    id: 'past-06',
    name: 'Paddock Maternidad y Sala Cuna',
    code: 'POT-06',
    areaHa: 4.5,
    grassType: 'Grama Puntero + Leguminosa Calopo',
    carryingCapacityUGM: 8,
    status: 'ocupado',
    entryDate: '2026-10-01',
    daysOccupied: 3,
    targetRestDays: 25,
    forageEstimateKgM2: 2.4,
    waterSource: 'bebedero_automatico',
    shadePercent: 50,
    notes: 'Zona protegida y vigilada con cámara para partos y terneraje.'
  }
];

export const INITIAL_MILK_RECORDS: MilkRecord[] = [
  {
    id: 'milk-01',
    date: '2026-10-03',
    shift: 'manana',
    animalId: 'anim-01',
    animalTag: 'CO-104',
    lotName: 'Lote Ordeño Principal',
    liters: 14.5,
    fatPercent: 3.9,
    proteinPercent: 3.3,
    somaticCellCount: 140000,
    californiaMastitisTest: 'negativo',
    destination: 'venta_planta',
    pricePerLiter: 0.52,
    revenue: 7.54
  },
  {
    id: 'milk-02',
    date: '2026-10-03',
    shift: 'manana',
    animalId: 'anim-02',
    animalTag: 'CO-109',
    lotName: 'Lote Ordeño Principal',
    liters: 11.2,
    fatPercent: 4.5,
    proteinPercent: 3.6,
    somaticCellCount: 180000,
    californiaMastitisTest: 'negativo',
    destination: 'venta_planta',
    pricePerLiter: 0.55,
    revenue: 6.16
  },
  {
    id: 'milk-03',
    date: '2026-10-03',
    shift: 'manana',
    animalId: 'anim-03',
    animalTag: 'CO-115',
    lotName: 'Lote Ordeño Principal',
    liters: 16.0,
    fatPercent: 3.6,
    proteinPercent: 3.1,
    californiaMastitisTest: 'grado_2',
    destination: 'descarte_antibiotico',
    notes: 'DESCARTE: Animal en tratamiento de antibiótico. Leche separada y desechada.'
  },
  {
    id: 'milk-04',
    date: '2026-10-02',
    shift: 'total_dia',
    lotName: 'Tanque Frío General',
    liters: 385,
    fatPercent: 4.1,
    proteinPercent: 3.4,
    temperatureTank: 3.8,
    destination: 'venta_planta',
    pricePerLiter: 0.53,
    revenue: 204.05,
    notes: 'Entrega a Carro Cisterna Colanta / Nestlé.'
  },
  {
    id: 'milk-05',
    date: '2026-10-01',
    shift: 'total_dia',
    lotName: 'Tanque Frío General',
    liters: 392,
    fatPercent: 4.0,
    proteinPercent: 3.35,
    temperatureTank: 4.0,
    destination: 'venta_planta',
    pricePerLiter: 0.53,
    revenue: 207.76
  }
];

export const INITIAL_WEIGHT_RECORDS: WeightRecord[] = [
  {
    id: 'weight-01',
    animalId: 'anim-06',
    animalTag: 'CO-305',
    date: '2026-09-30',
    weightKg: 420,
    previousWeightKg: 385,
    daysBetween: 30,
    adgKg: 1.167,
    weighingType: 'rutina',
    bodyCondition: 4.25,
    notes: 'Excelente respuesta a suplementación con silo y torta de palmiste.'
  },
  {
    id: 'weight-02',
    animalId: 'anim-07',
    animalTag: 'CO-308',
    date: '2026-09-30',
    weightKg: 395,
    previousWeightKg: 368,
    daysBetween: 30,
    adgKg: 0.900,
    weighingType: 'rutina',
    bodyCondition: 3.75
  },
  {
    id: 'weight-03',
    animalId: 'anim-08',
    animalTag: 'CO-402',
    date: '2026-09-15',
    weightKg: 360,
    previousWeightKg: 335,
    daysBetween: 35,
    adgKg: 0.714,
    weighingType: 'servicio',
    bodyCondition: 3.5,
    notes: 'Apta reproductivamente para primera inseminación artificial.'
  }
];

export const INITIAL_REPRODUCTION_EVENTS: ReproductionEvent[] = [
  {
    id: 'rep-01',
    animalId: 'anim-01',
    animalTag: 'CO-104',
    eventType: 'ecografia',
    date: '2026-08-20',
    sireTagOrStraw: 'SEMEN-HOL-CHIEF',
    pregnancyStatus: 'positivo',
    estimatedGestationDays: 56,
    expectedCalvingDate: '2027-04-04',
    inseminator: 'Dr. Medina (Veterinario)',
    observations: 'Feto viable con latido cardíaco claro. Gestación confirmada.'
  },
  {
    id: 'rep-02',
    animalId: 'anim-08',
    animalTag: 'CO-402',
    eventType: 'celo',
    date: '2026-10-03',
    observations: 'Reflejo de inmovilidad y moco cristalino abundante. Programar IA a las 18:00 hrs.'
  },
  {
    id: 'rep-03',
    animalId: 'anim-04',
    animalTag: 'CO-128',
    eventType: 'secado',
    date: '2026-08-20',
    dryOffTreatment: 'Tubo de secado Ubrostar + Sellador de pezones externo',
    observations: 'Secado completado a los 220 días de gestación. Pasa a potrero de escoteras.'
  }
];

export const INITIAL_HEALTH_RECORDS: HealthRecord[] = [
  {
    id: 'health-01',
    animalId: 'anim-03',
    animalTag: 'CO-115',
    type: 'tratamiento_clinico',
    date: '2026-10-02',
    diseaseOrReason: 'Mastitis Clínica Aguda (Streptococcus uberis)',
    medicationName: 'Cefalexina Intramamaria 200mg + Flunixin Meglumine',
    dosage: '1 jeringa c/12h por 3 días + 10ml IM',
    administrationRoute: 'intramamaria',
    batchNumber: 'LOT-9921B',
    veterinarian: 'Dr. Medina',
    withdrawalDaysMilk: 4,
    withdrawalDaysMeat: 14,
    withdrawalEndDate: '2026-10-06',
    cost: 45.0,
    status: 'en_curso',
    notes: 'Pezo inflamado y leche con grumos. Aislamiento preventivo.'
  },
  {
    id: 'health-02',
    animalId: 'TODOS',
    animalTag: 'LOTE GENERAL (120 Cabezas)',
    type: 'vacuna',
    date: '2026-05-15',
    diseaseOrReason: 'Ciclo Oficial Vacunación Fiebre Aftosa y Brucelosis Bovina',
    medicationName: 'Aftogan Bivalente + Cepa 19 Brucelosis',
    dosage: '2 ml Subcutánea por animal',
    administrationRoute: 'subcutanea',
    batchNumber: 'ICA-2026-044',
    veterinarian: 'Comité de Ganaderos / ICA',
    withdrawalDaysMilk: 0,
    withdrawalDaysMeat: 0,
    cost: 320.0,
    status: 'aplicado',
    notes: 'Certificado oficial de vacunación RUV No. 8849201 expedido.'
  },
  {
    id: 'health-03',
    animalId: 'TODOS_CEBA',
    animalTag: 'Lote Ceba Lote A',
    type: 'desparasitacion',
    date: '2026-09-01',
    diseaseOrReason: 'Control de parásitos gastrointestinales y garrapatas',
    medicationName: 'Ivermectina 3.15% Larga Acción',
    dosage: '1 ml cada 50 kg PV',
    administrationRoute: 'subcutanea',
    batchNumber: 'IVM-2026-8',
    veterinarian: 'Carlos Mendoza',
    withdrawalDaysMilk: 0,
    withdrawalDaysMeat: 28,
    cost: 110.0,
    status: 'aplicado'
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-01',
    category: 'balanceado_concentrado',
    name: 'Concentrado Lechero 18% Proteína (Saco 40kg)',
    skuCode: 'CONC-LEC-18',
    unit: 'sacos_40kg',
    currentStock: 65,
    minStockAlert: 20,
    unitCost: 28.5,
    supplier: 'Italcol / Solla Nutrición',
    location: 'Bodega Principal Estiba 1'
  },
  {
    id: 'inv-02',
    category: 'silo_heno',
    name: 'Silo de Maíz Enbolsado Alta Energía',
    skuCode: 'SILO-MAIZ-50K',
    unit: 'toneladas',
    currentStock: 18.5,
    minStockAlert: 5.0,
    unitCost: 85.0,
    supplier: 'Cultivo propio Finca San Jerónimo',
    location: 'Silo Trinchera B'
  },
  {
    id: 'inv-03',
    category: 'sal_mineral',
    name: 'Sal Mineralizada Ganado Cría 8% Fósforo',
    skuCode: 'SAL-MIN-8P',
    unit: 'sacos_40kg',
    currentStock: 14,
    minStockAlert: 8,
    unitCost: 22.0,
    supplier: 'Somex Minerales',
    location: 'Bodega Saleros'
  },
  {
    id: 'inv-04',
    category: 'medicamento',
    name: 'Oxitetraciclina L.A. 200mg (Frasco 250ml)',
    skuCode: 'MED-OXI-250',
    unit: 'frascos',
    currentStock: 6,
    minStockAlert: 3,
    unitCost: 19.5,
    expirationDate: '2027-11-30',
    supplier: 'Zoetis Veterinaria',
    location: 'Botiquín Farmacia Veterinaria'
  },
  {
    id: 'inv-05',
    category: 'medicamento',
    name: 'Cefalexina Intramamaria Tubos Lactancia (Caja 20u)',
    skuCode: 'MED-CEF-TUB',
    unit: 'unidades',
    currentStock: 12,
    minStockAlert: 10,
    unitCost: 2.8,
    expirationDate: '2027-04-15',
    supplier: 'Virbac Salud Animal',
    location: 'Botiquín Farmacia Veterinaria'
  },
  {
    id: 'inv-06',
    category: 'vacuna',
    name: 'Vacuna Clostridial 8 Vías (Frasco 50 Dosis)',
    skuCode: 'VAC-CLOS-8V',
    unit: 'dosis',
    currentStock: 150,
    minStockAlert: 50,
    unitCost: 0.85,
    expirationDate: '2027-02-28',
    supplier: 'MSD Salud Animal',
    location: 'Nevera Biológicos (4°C)'
  },
  {
    id: 'inv-07',
    category: 'pajilla_semen',
    name: 'Pajillas Semen Toro Girolando 5/8 (Gimonte)',
    skuCode: 'SEM-GIR-GIM',
    unit: 'pajillas',
    currentStock: 28,
    minStockAlert: 10,
    unitCost: 18.0,
    supplier: 'ABS Global Genética',
    location: 'Termo Criogénico MVE XC 34/18 - Canastilla 2'
  },
  {
    id: 'inv-08',
    category: 'arete_identificacion',
    name: 'Aretes Visuales Grandes + Botón RFID SENASA/ICA',
    skuCode: 'ART-RFID-DUO',
    unit: 'unidades',
    currentStock: 45,
    minStockAlert: 20,
    unitCost: 3.2,
    supplier: 'Allflex Livestock Intelligence',
    location: 'Bodega Principal Cajón 3'
  }
];

export const INITIAL_SEMEN_STRAWS: SemenStraw[] = [
  {
    id: 'sem-01',
    bullName: 'Gimonte Teatro FIV (Girolando 5/8)',
    registrationCode: 'GIR-BRA-88912',
    breed: 'Girolando',
    canisterNumber: 'Canastilla 1',
    gobletColor: 'Amarillo',
    quantityAvailable: 18,
    unitCost: 22.0,
    supplier: 'ABS Global',
    geneticProof: 'PTA Leche +920 kg, Longevidad +4.1, Facilidad Parto 99%'
  },
  {
    id: 'sem-02',
    bullName: 'Jaguar TE do Gaviao (Gyr Puro)',
    registrationCode: 'GYR-BR-4402',
    breed: 'Gyr Lechero',
    canisterNumber: 'Canastilla 2',
    gobletColor: 'Verde',
    quantityAvailable: 10,
    unitCost: 35.0,
    supplier: 'Alta Genetics',
    geneticProof: 'PTA Leche +1,180 kg, Sólidos Totales +0.22%, Ubre 2.8'
  },
  {
    id: 'sem-03',
    bullName: 'Mr. V8 191/7 "El Magnífico" (Brahman Gris)',
    registrationCode: 'BR-USA-99218',
    breed: 'Brahman',
    canisterNumber: 'Canastilla 3',
    gobletColor: 'Rojo',
    quantityAvailable: 15,
    unitCost: 28.0,
    supplier: 'Semex Internacional',
    geneticProof: 'DEP Peso Destete +24 kg, DEP Peso 18m +42 kg, Área Ojo Lomo +3.1'
  }
];

export const INITIAL_TRANSACTIONS: FinancialTransaction[] = [
  {
    id: 'tx-01',
    date: '2026-10-02',
    type: 'ingreso',
    category: 'venta_leche',
    amount: 1428.35,
    concept: 'Liquidación Quincenal Venta de Leche (2,695 Litros a Planta Procesadora)',
    quantity: 2695,
    unitPrice: 0.53,
    paymentStatus: 'cobrado',
    invoiceNumber: 'FAC-LECH-8821'
  },
  {
    id: 'tx-02',
    date: '2026-09-28',
    type: 'ingreso',
    category: 'venta_ganado_pie',
    amount: 5460.00,
    concept: 'Venta de 6 Novillos Gordos de Ceba a Frigorífico Regional (2,730 kg en pie)',
    quantity: 6,
    unitPrice: 910.0,
    paymentStatus: 'cobrado',
    invoiceNumber: 'FAC-GAN-0341'
  },
  {
    id: 'tx-03',
    date: '2026-09-25',
    type: 'egreso',
    category: 'compra_alimento',
    amount: 1140.00,
    concept: 'Compra de 40 Sacos Concentrado Lechero 18% Proteína + 10 Sacos Sal Mineral',
    paymentStatus: 'pagado',
    invoiceNumber: 'FAC-PROV-5510'
  },
  {
    id: 'tx-04',
    date: '2026-09-30',
    type: 'egreso',
    category: 'jornales_personal',
    amount: 1850.00,
    concept: 'Nómina y Jornales Quincenales: 1 Mayordomo, 2 Ordeñadores, 1 Vaquero',
    paymentStatus: 'pagado'
  },
  {
    id: 'tx-05',
    date: '2026-09-20',
    type: 'egreso',
    category: 'veterinario_asesoria',
    amount: 280.00,
    concept: 'Honorarios Chequeo Reproductivo Ginecológico y Ecografías (Dr. Medina)',
    paymentStatus: 'pagado'
  },
  {
    id: 'tx-06',
    date: '2026-09-18',
    type: 'egreso',
    category: 'combustible',
    amount: 220.00,
    concept: 'Combustible ACPM / Diésel para Tractor Massey Ferguson y Picadora de Pasto',
    paymentStatus: 'pagado'
  }
];

export const INITIAL_TASKS: TaskAssignment[] = [
  {
    id: 'task-01',
    title: 'Inseminación Artificial Novilla CO-402',
    description: 'Novilla Princesa Simmental en celo franco. Aplicar pajilla Mr. V8 o Simmentaler a las 18:00.',
    category: 'reproduccion',
    dueDate: '2026-10-03',
    priority: 'urgente',
    assignedTo: 'Carlos Mendoza (Mayordomo)',
    completed: false,
    relatedAnimalTag: 'CO-402'
  },
  {
    id: 'task-02',
    title: 'Control y 3ra dosis tratamiento Mastitis CO-115',
    description: 'Aplicar tubo intramamario Cefalexina post-ordeño de la tarde. Descartar leche sin mezclar.',
    category: 'sanidad',
    dueDate: '2026-10-04',
    priority: 'urgente',
    assignedTo: 'Juan Pérez (Ordeñador)',
    completed: false,
    relatedAnimalTag: 'CO-115'
  },
  {
    id: 'task-03',
    title: 'Rotación Lote Ceba de Potrero 02 a Potrero 05',
    description: 'Mover los 25 novillos de ceba al potrero Los Samanes (cumplió 30 días de descanso).',
    category: 'rotacion_potrero',
    dueDate: '2026-10-05',
    priority: 'alta',
    assignedTo: 'Marcos Rivas (Vaquero)',
    completed: false
  },
  {
    id: 'task-04',
    title: 'Pesaje Mensual Lote Novillas de Vientre',
    description: 'Pasar por báscula romana a las 15 novillas para verificar ganancia de peso pre-servicio.',
    category: 'pesaje',
    dueDate: '2026-10-08',
    priority: 'media',
    assignedTo: 'Carlos Mendoza',
    completed: false
  },
  {
    id: 'task-05',
    title: 'Preparación de Silo y Ración de Tarde',
    description: 'Picar forraje y mezclar 200kg silo de maíz con sal mineral y melaza para suplementar.',
    category: 'nutricion',
    dueDate: '2026-10-03',
    priority: 'alta',
    assignedTo: 'Marcos Rivas',
    completed: true
  }
];

export const INITIAL_PADDOCK_NOVELTIES: import('../types/livestock').PaddockNovelty[] = [
  {
    id: 'nov-01',
    date: '2026-10-04',
    time: '06:45',
    pastureId: 'past-06',
    pastureName: 'Paddock Maternidad y Sala Cuna',
    lotName: 'Lote Sala Cuna / Terneras',
    type: 'parto_nacimiento',
    severity: 'info',
    animalTag: 'CO-104',
    calfTag: 'CO-509',
    calfSex: 'F',
    calfWeightKg: 38.5,
    description: 'Nacimiento exitoso en recorrida matutina. Ternera vigorosa, mamó calostro a la primera hora. Madre limpia sin retención.',
    reportedBy: 'Marcos Rivas (Vaquero)',
    status: 'resuelto',
    createdAt: '2026-10-04T06:45:00Z'
  },
  {
    id: 'nov-02',
    date: '2026-10-03',
    time: '07:15',
    pastureId: 'past-02',
    pastureName: 'Potrero La Vega (Ceba Intensiva)',
    lotName: 'Lote Engorde Lote A',
    type: 'falla_infraestructura',
    infraType: 'bebedero_sin_agua',
    severity: 'urgente',
    description: 'Válvula de flotador del bebedero principal atascada con sedimentos. Nivel de agua bajo. Requiere limpieza inmediata.',
    reportedBy: 'Marcos Rivas (Vaquero)',
    status: 'en_atencion',
    createdAt: '2026-10-03T07:15:00Z'
  },
  {
    id: 'nov-03',
    date: '2026-10-02',
    time: '16:30',
    pastureId: 'past-01',
    pastureName: 'Potrero La Florida (Ordeño)',
    lotName: 'Lote Ordeño Principal',
    type: 'enfermo_herido',
    severity: 'alerta',
    animalTag: 'CO-115',
    causeOrReason: 'Mastitis Clínica Cuarto Trasero Izquierdo',
    description: 'Vaca apartada con inflamación evidente y grumos en prueba de fondo negro. Se inició protocolo cefalexina intramamaria.',
    reportedBy: 'Juan Pérez (Ordeñador)',
    status: 'en_atencion',
    createdAt: '2026-10-02T16:30:00Z'
  },
  {
    id: 'nov-04',
    date: '2026-10-01',
    time: '08:00',
    pastureId: 'past-03',
    pastureName: 'Potrero Las Palmas (Escoteras)',
    lotName: 'Lote Vacas Horras y Escoteras',
    type: 'recorrida_ok',
    severity: 'info',
    description: 'Recorrida completa del potrero: bebedero limpio con buen caudal, cerca eléctrica con 7.8 kV, saladero techado con sal mineral al 8%. Hato tranquilo.',
    reportedBy: 'Carlos Mendoza',
    status: 'resuelto',
    createdAt: '2026-10-01T08:00:00Z'
  }
];

export const INITIAL_HERD_ROTATIONS: import('../types/livestock').HerdRotationRecord[] = [
  {
    id: 'rot-01',
    date: '2026-09-28',
    lotName: 'Lote Engorde Lote A',
    sourcePastureId: 'past-05',
    sourcePastureName: 'Potrero Los Samanes',
    targetPastureId: 'past-02',
    targetPastureName: 'Potrero La Vega (Ceba Intensiva)',
    expectedHeads: 25,
    countedHeads: 25,
    discrepancy: 0,
    responsiblePerson: 'Carlos Mendoza & Marcos Rivas',
    pastureForageState: 'optimo',
    notes: 'Conteo en manga exacto (25/25 cabezas). Entrada a pasto Mombaza con 3.4 kg/m² de aforo verde.',
    createdAt: '2026-09-28T09:30:00Z'
  },
  {
    id: 'rot-02',
    date: '2026-09-24',
    lotName: 'Lote Ordeño Principal',
    sourcePastureId: 'past-04',
    sourcePastureName: 'Potrero El Repostero',
    targetPastureId: 'past-01',
    targetPastureName: 'Potrero La Florida (Ordeño)',
    expectedHeads: 28,
    countedHeads: 28,
    discrepancy: 0,
    responsiblePerson: 'Juan Pérez',
    pastureForageState: 'optimo',
    notes: 'Paso por manga de ordeño completo. Excelente comportamiento del lote.',
    createdAt: '2026-09-24T06:00:00Z'
  }
];

export const INITIAL_RODEO_AUDITS: import('../types/livestock').DailyRodeoAudit[] = [
  {
    id: 'audit-01',
    date: '2026-10-04',
    pastureId: 'past-01',
    pastureName: 'Potrero La Florida (Ordeño)',
    waterStatus: 'optimo_limpio',
    fenceStatus: 'intacta_buen_voltaje',
    saltStatus: 'abundante',
    generalHealth: 'excelente',
    checkedBy: 'Marcos Rivas (Vaquero)',
    notes: 'Todo en orden. Bebedero limpio, voltaje en 8.2 kV.',
    timestamp: '2026-10-04T06:30:00Z'
  },
  {
    id: 'audit-02',
    date: '2026-10-04',
    pastureId: 'past-02',
    pastureName: 'Potrero La Vega (Ceba Intensiva)',
    waterStatus: 'escaso',
    fenceStatus: 'intacta_buen_voltaje',
    saltStatus: 'medio',
    generalHealth: 'novedades_reportadas',
    checkedBy: 'Marcos Rivas (Vaquero)',
    notes: 'Bebedero requiere desatascar flotador.',
    timestamp: '2026-10-04T07:00:00Z'
  }
];

